### ISSUE TITLE
CASE/unrealistic_high_pm25

### ISSUE THREAD

**Issue by lipan-NOAA** [noaa-oar-arl/UFS-Aerosol-Config#20]
## Case Details: 
cd /scratch1/NCEPDEV/stmp4/Li.Pan/COM/firex_1/logs/2019070100
grep -ni "pm25 max" gfs.forecast.highres.log
8390: pm25 max =    2101.25335386130       min =   9.947723530538242E-027
11148: pm25 max =    **201247.049626711**       min =   9.823742736999839E-027
13858: pm25 max =    **9203631372.33169**       min =   9.681838852327386E-027
16568: pm25 max =   **2.147749677365294E+020**  min =   9.730520599258893E-027

## Model Configuration Details 
- Resolution: C384L64
- Begin Date: 2019070100
- End Date: 2019070200
- Cold Start: True
- Forecast length (FHMAX_GFS): 24 hours
- FV3 output: every 6 hours 

## Aerosol Model Configuration
rcfile=/scratch2/NCEPDEV/naqfc/Li.Pan/save/data/NASA/rc.firex
logfile=/scratch1/NCEPDEV/stmp4/Li.Pan/COM/firex_1/logs/2019070100/gfs.forecast.highres.log
rundir=/scratch2/NCEPDEV/stmp1/Li.Pan/chem202108/firex_1
homgfs=/scratch2/NAGAPE/arl/Li.Pan/global-workflow

**Comment by bbakernoaa** [comment]
@lipan-NOAA could you give a little more context for what is happening? Is
this extremely localized and does it persist? Is this due to a specific
species (OC, BC or DUST)? What is the wet scavenging settings?

I noticed that you did not use the latest develop branch for your
configuration files. There are several updates and we have been seeing
fairly stable runs.

What branch of the UFS-Aerosols are you using? Is this the feature/p7.1?

**Comment by lipan-NOAA** [comment]
@bbakernoaa It happened everywhere near the surface for all species. I did not do any changes on scavenging settings, which are defined in rc.file.  And I compared my rc.file to Kate's, except for extdata.rc and history.rc, there are no big differences. Since I am focusing on engineering test at this moment, I don't think it will make big differences. 

I am still using feature/aerosols, and I am going to upgrade it to feature/p7.1.

**Comment by bbakernoaa** [comment]
@lipan-NOAA. I highly suggest you upgrade to feature/p7.1 there a few fixes
in it and use the develop branch of this repository for the configuration
files.

Could you provide some plots?

Btw the scavenging factors are not set in the .rc files. The values must be
present in those values but only used internally for nasa. The values used
in UFS-Aerosols are found in your case yaml file.

Please use the configuration repository so that we can keep track of
setting and are sure of the co figurations. We went through this with GEFS
and were never completely sure what exactly was being done.

**Comment by rmontuoro** [comment]
@lipan-NOAA - Your global-workflow directory (`/scratch2/NAGAPE/arl/Li.Pan/global-workflow/sorc/ufs_coupled.fd`) shows that your experiment used a code revision _not recommended_ for testing:

url: [https://github.com/ufs-community/ufs-weather-model](https://github.com/ufs-community/ufs-weather-model)
hash: [22613e8 (July 20)](https://github.com/ufs-community/ufs-weather-model/tree/22613e80738f342fb0efd83b8c11602465fe51b3)

This version does not include a crucial update to the convective transport that fixes the unrealistic high mixing ratios you reported. The update was applied on August 12.

Please follow the instructions listed in issue #14 and ***do not*** use model revisions other than those recommended in issue #14.
