### ISSUE TITLE
Evaluation of P7.2 experiments

### ISSUE THREAD

**Issue by rmontuoro** [noaa-oar-arl/UFS-Aerosol-Config#33]
This issue aims to summarize evaluation work and discussions on the results of mini-P7.2 experiments completed recently.

The output from those experiments is available on HPSS: `/NCEPDEV/emc-climate/1year/Jiande.Wang/HERA/scratch/UFS-P7.2`

The mini-P7.2 prototype is based on the ufs-weather-model revision [c1d6d19](https://github.com/ufs-community/ufs-weather-model/commit/c1d6d19d615363d8443ddc15c2a7a9c3dc7bc5f9) (Oct. 7) and included the following differences with respect to P7.1:
* Setting `cdmbgwd="1.0,2.2,1.0,1.0"` for parameterized orographic gravity-wave drag
* CA was unintentionally turned off (will be turned back on in future prototypes)
* Updated Initial conditions for the atmosphere and wave model

**Comment by zhanglikate** [comment]
@rmontuoro “CA was unintentionally turned off ”， what is about CA? Thanks.

**Comment by ghost** [comment]
@rmontuoro @zhanglikate 
I have started looking into protoype 7.2 results, here is comparison against MERRA2 total AOD for all 4 initial times in week1, 2 and 3&4 together (bias and RMSE). Most error associated with july run (because of active fire season). 
https://docs.google.com/presentation/d/1OTyZgAtWcNZb1hDJMJI8jI7OyxRGKq-Y/edit?usp=sharing&ouid=100966050662930876047&rtpof=true&sd=true

I will be updating this ppt link.

**Comment by drpeppurr** [comment]
@rmontuoro I've been using ATom observations (2016-2018) for evaluation. It seems you have outputs for 2012-2013...? Could you elaborate on what you would expected us (here at CSL) to do please? Thank you.

**Comment by rmontuoro** [comment]
> @rmontuoro I've been using ATom observations (2016-2018) for evaluation. It seems you have outputs for 2012-2013...? Could you elaborate on what you would expected us (here at CSL) to do please? Thank you.

@drpeppurr - No expectations from CSL at all. Just wanted to share our P7.2 results with the entire team.
